version: '3'
services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_apache
    volumes:
      - ./app/:/var/www/app
    networks:
      - laravel
    ports:
      - 80:80
#database configuration app
  mysql_app:
    image: mysql:5.7
    container_name: laravel_mysql
    networks:
      - laravel
    volumes:
      - "./data/:/var/lib/mysql"
      - "./dump/:/docker-entrypoint-initdb.d"
      - "./config-docker/sql/:/etc/mysql/conf.d"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
#pma configuration app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_pma
    networks:
      - laravel
    ports:
      - 8080:80
    environment:
      PMA_HOST: laravel_mysql

#define network
networks:
  laravel:
    driver: bridge
